import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'

export const metadata: Metadata = {
  title: 'Sensative web-app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={GeistSans.className} suppressHydrationWarning>
      <body className={''}>
        <main className='flex min-h-screen flex-col justify-center items-center'>{children}</main>
      </body>
    </html>
  )
}
