import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";

import { NavBar } from "@/components/nav/navbar";

export const metadata: Metadata = {
  title: "Sensative web-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={` ${GeistSans.className}`}
      suppressHydrationWarning
    >
      <body className={"h-full"}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
