import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";

import { NavBar } from "@/components/nav/navbar";
import Providers from "./providers";
import { ReactQueryClientProvider } from "@/components/query-provider";

export const metadata: Metadata = {
  title: "Sensative web-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={` ${GeistSans.className}`}
      suppressHydrationWarning
    >
      <body className={"h-full"}>
        <NavBar />
        <Providers>{children}</Providers>
        {/* <ReactQueryClientProvider>{children}</ReactQueryClientProvider> */}
      </body>
    </html>
  );
}
